### ISSUE TITLE
path must be a string or Buffer

### ISSUE THREAD

**Issue by aredfox** [vot/ffbinaries-node#4]
When using the API, I get following error - below the error is the gulp-task I use.
Using Windows 7 (64bit) - node 7.0.0 - ffbinaries 0.1.5

**Error**:<br/>

```
SCHELPEY@AKDGPORT6348 C:\Dev\Repos\Kdg.Xtl4
> gulp build --prod
[14:37:39] Using gulpfile C:\Dev\Repos\Kdg.Xtl4\gulpfile.js
[14:37:39] Starting 'build'...
[14:37:39] Starting 'build:clean'...
[14:37:39] Finished 'build:clean' after 33 ms
[14:37:39] Starting 'copy:data'...
[14:37:39] Starting 'copy:ffmpeg'...
Trying to download FFMPEG for windows-64 to C:\Dev\Repos\Kdg.Xtl4\app\lib\ffmpeg...
Directories
 LOCAL_CACHE_DIR: C:\Users\SCHELPEY/.ffbinaries-cache
 CWD: C:\Dev\Repos\Kdg.Xtl4
------------------------------------
[14:37:39] 'copy:ffmpeg' errored after 868 μs
[14:37:39] TypeError: path must be a string or Buffer
    at Object.fs.mkdirSync (fs.js:846:18)
    at _ensureDirSync (C:\Dev\Repos\Kdg.Xtl4\node_modules\ffbinaries\ffbinaries-lib.js:20:9)
    at Object.downloadFiles (C:\Dev\Repos\Kdg.Xtl4\node_modules\ffbinaries\ffbinaries-lib.js:274:3)
    at Gulp.<anonymous> (C:\Dev\Repos\Kdg.Xtl4\gulp\tasks\copy\copy.ffmpeg.js:15:31)
    at module.exports (C:\Dev\Repos\Kdg.Xtl4\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Dev\Repos\Kdg.Xtl4\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Dev\Repos\Kdg.Xtl4\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\Dev\Repos\Kdg.Xtl4\node_modules\orchestrator\index.js:134:8)
    at runNextSet (C:\Dev\Repos\Kdg.Xtl4\node_modules\run-sequence\index.js:86:16)
    at Gulp.onTaskEnd (C:\Dev\Repos\Kdg.Xtl4\node_modules\run-sequence\index.js:75:5)
[14:37:39] 'build' errored after 50 ms
[14:37:39] TypeError in plugin 'run-sequence(copy:ffmpeg)'
Message:
    path must be a string or Buffer
Stack:
TypeError: path must be a string or Buffer
    at Object.fs.mkdirSync (fs.js:846:18)
    at _ensureDirSync (C:\Dev\Repos\Kdg.Xtl4\node_modules\ffbinaries\ffbinaries-lib.js:20:9)
    at Object.downloadFiles (C:\Dev\Repos\Kdg.Xtl4\node_modules\ffbinaries\ffbinaries-lib.js:274:3)
    at Gulp.<anonymous> (C:\Dev\Repos\Kdg.Xtl4\gulp\tasks\copy\copy.ffmpeg.js:15:31)
    at module.exports (C:\Dev\Repos\Kdg.Xtl4\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Dev\Repos\Kdg.Xtl4\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Dev\Repos\Kdg.Xtl4\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\Dev\Repos\Kdg.Xtl4\node_modules\orchestrator\index.js:134:8)
    at runNextSet (C:\Dev\Repos\Kdg.Xtl4\node_modules\run-sequence\index.js:86:16)
    at Gulp.onTaskEnd (C:\Dev\Repos\Kdg.Xtl4\node_modules\run-sequence\index.js:75:5)
[14:37:39] Finished 'copy:data' after 68 ms
```

**Gulp Task**:<br/>
The gulp task is seperated, inside plugins is ffbinaries named as ffmpeg. It spits out the correct platform for me, as you can see in the logs above. The outputfolder gets generated ok as well. I think the error resides somewhere in downloadFiles but I'm a bit lost.. Will try this on linux as well and report when I know more.<br/>
```
module.exports = (gulp, plugins) => {
    return () => {
        const platform = plugins.ffmpeg.detectPlatform();
        const outputFolder = plugins.path.resolve(plugins.path.join(plugins.config.paths.dest.lib, 'ffmpeg', '\\'));
        console.log(`Trying to download FFMPEG for ${platform} to ${outputFolder}...`);
        return plugins.ffmpeg.downloadFiles(platform, outputFolder.toString(), () => {
            console.log('Downloaded binaries for ' + platform + ' to ' + outputFolder + '.');
        });
    };
};
```

**Comment by aredfox** [comment]
**Linux Update**: *Linux-64 bit (v. Linux MINT 18.1)* has the same error/issue: `TypeError: path must be a string or Buffer` occuring at `Object.fs.mkdirSync`.

Should I maybe make sure the path exists first?

**Comment by aredfox** [comment]
**Solved**<br/>
Misread docs, I'm sorry, when inspecting line 274:3 in ffbinaries-lib.js I saw opts was an object with prop dest (and possible others props).

Changed code to:<br/>
```
module.exports = (gulp, plugins) => {
    return () => {
        const platform = plugins.ffmpeg.detectPlatform();
        const outputFolder = plugins.path.resolve(plugins.path.join(plugins.config.paths.dest.lib, 'ffmpeg', '\\'));
        require('shelljs').mkdir('-p', outputFolder);
        console.log(`Trying to download FFMPEG for ${platform} to ${outputFolder}...`);
        return plugins.ffmpeg.downloadFiles(platform, { destination: outputFolder.toString() }, () => {
            console.log('Downloaded binaries for ' + platform + ' to ' + outputFolder + '.');
        });
    };
};
```

**Suggestion:**<br/>
Maybe add properties documentation for the downloadFiles function, with a description. I'll try to make a suggestion/PR for this.

**Comment by aredfox** [comment]
ps, @vot - I do want to add this library is **magic** - so thanks for putting in the effort. It solves a lot of manual work!

**Comment by vot** [comment]
Ah sorry, this is entirely on me - I should've updated the documentation to include all of this. I think I must've changed the function signature at some point and never realised that part of readme is out of sync.

I've been mostly testing this on CLI as I don't have a proper implementation yet in my other projects... bit of a shame but I'm glad it's already helping other people out :)
